[2023-04-06 21:08:35] [INFO] [classify_api.py]/[line: 72]/[update] {'errno': 505, 'errmsg': '更新数据失败'} 
